---
title: "Research Goals"
output: 
  html_document: 
    fig_caption: yes
    toc: yes
    toc_float: true
---

<style type="text/css">

h1.title {
  font-size: 38px;
  color: #232D4B;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: #E57200;
}
h2 { /* Header 2 */
    font-size: 22px;
  color: #666666;
}
h3 { /* Header 3 */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: #141E3C;
}
</style>

# Machine learning... 

to promote collective citizen capacity

1. Generate

 - a dynamic representation of presidentially-relevant news
 - but also, research questions 
 - and hands-on educational experiences  

2. Some inspirations

 - polling aggregation, as epitomized by site's like Nate Silver's 538
 - distant reading, not studying the news, but consuming a greater quantity of news via machine reading

3. Why this makes sense in my continually evolving understanding of libraries

 - The vanguard of democratizing information by lowering barriers to access
 - Connected to expansion from information access to information use
 - Alignment with [core library values](http://www.ala.org/advocacy/intfreedom/corevalues): promoting equal information access and use, enabling democratic governance, and contributing to the public good.

<div style="margin-bottom:50px;">
</div>

# Related efforts (sort of)

Additonal notes on these are [here](https://github.com/datafordemocracy/publicpresidency/blob/master/notetoself.md); ping me if there's something I should add to the evolving list!

## Profit-oriented

Methods are not open/transparent (proprietary), sources aren't known, content is not free...

* [Aylien's news search api](https://aylien.com/news-api/), provides number of stories and features baesd on search terms
* Lexis-Nexis [Newsdesk](https://www.lexisnexis.com/en-us/products/newsdesk.page), acquired Moreover, a media monitoring and news aggregation service
* IBM [Watson Discovery News](https://www.ibm.com/watson/services/discovery-news/), acquired 
[Alchemy DataNews API](https://github.com/AlchemyAPI), proivdes top stories and features based on search terms  

## Academic- or public-oriented

* [Vanderbilt TV News archive](https://tvnews.vanderbilt.edu/), searchable database of story abstracts from ABC, CBS, NBC, CNN, Fox newscasts
* [Internet Archive's TV News archive](https://archive.org/details/tv): search closed-caption transcripts divided into 60 second segments
* [GDELT Summary Television Explorer](https://api.gdeltproject.org/api/v2/summary/summary?DATASET=IATV&TYPE=SUMMARY&STARTDATETIME=&ENDDATETIME=), working with TV news archive, returns summaries of appearance of search term (`newsflash`](https://github.com/hrbrmstr/newsflash), an R package for interacting with IA/GDELT)
* [GDELT (broadly)](https://www.gdeltproject.org/), "monitors the world's broadcast, print, and web news from nearly every corner of every country in over 100 languages" 
* [UCLA communication archive](https://tvnews.sscnet.ucla.edu/public/), returns clips containing search term
* [Newsreader](http://www.newsreader-project.eu/news-events/news/) project, event data focused (currently maintained?)

