---
title: "Imagining New Ways to Engage Political News"
author: Michele Claibourn
date: "April 17, 2018"
output: 
  html_document: 
    fig_caption: yes
    toc: yes
    toc_float: true
---

## ... Starting with the Presidency

### or, Monitoring Presidential Information Streams

The initial project of the [Data for Democracy Lab @ UVA](https://datafordemocracy.github.io/public-presidency/), The Public Presidency Project, began to form after a series of conversations with people from a variety of perspectives who consistently communicated: “I can’t read/watch the news anymore. It’s too…[exhausting, depressing, distracting, anger-inducing, polarizing, … ].”

That’s a problem. It’s not like democratic citizens have ever been acclaimed for their political attentiveness, but at the end of the day, we need to have some idea of what’s going on. Accountability, you know.

So we began thinking about the various challenges – of echo chambers and filter bubbles, of an increasingly complex media environment, of a media environment where news standards have degraded, of scarcity of time and emotional effort, of unequal access to information, and more – and wondering if it isn’t time to begin imagining and developing new ways for the public to engage political news. (Yes, yes it is.)

This project takes news about the presidency as the initial domain of interest – though there’s no particular reason we couldn’t generalize to additional areas – to begin exploring what it might mean to extract (and present) substantive and useful features from presidential representations, of rhetorical attention and activity, as represented by a range of diverging news and information sources.